### PR TITLE
Fix nonuniformly separated orbit points in ellipse.js. 

### PR DESCRIPTION
**Pull request by nomad-vagabond**
Instead of using time parameter for orbit points generation better use angular parameter. You can get more or less uniformly separated points along the orbit path and use much less points. Very useful for orbits with high eccentricity. Moreover, this fix eliminates orbit lines overlapping.

### CODE REVIEW

**Comment by typpo** [comment]
Thank you for this!  👍

**Comment by nomad-vagabond** [comment]
Any time! What do you think about adding some extra features to Asterank, particularly – identification of close approaching asteroids (aka potentially hazardous)?

**Comment by typpo** [comment]
I would love to see that feature, especially if you're interested in developing it.  Let me know if you'd like to discuss further, or just send over a pull request. :)

**Comment by nomad-vagabond** [comment]
I've sent you a letter on the e-mail specified at your website. If you haven't received it, please, let me know.

**Pull request merged**
